### ISSUE TITLE
Exceptions in pure code

### ISSUE THREAD

**Issue by ford-prefect** [purescript-contrib/purescript-aff#172]
Currently, if we have bad code that throws an exception despite being annotated as being pure, it seems to put `Aff` into a bad state where no more callbacks occur. I've written up an example at:

    https://github.com/ford-prefect/purescript-sandbox

This is of course just bad code, but it _might_ make sense to be defensive against this if there isn't a significant cost, as there are cases with a significant surface of JS interop, which can make for more common programming errors.

**Comment by ford-prefect** [comment]
@natefaubion you mentioned performance concerns w.r.t. adding try/catches to deal with such programming errors. Is this something you've quantified (or that we could try to)? Might help make a more informed decision about the cost.

**Comment by natefaubion** [comment]
There are some basic benchmarks in the repo for pure binds. I would run it as is, apply a try/catch around the `STEP_BIND` case in the interpreter, and then see what the difference is. If there is a significant performance degradation, then I would try lifting the try/catch out of the main loop like we do for `runSync` and benchmark that.

**Comment by ford-prefect** [comment]
Thanks @natefaubion -- I don't see a perf impact in the benchmark. `pulp test` takes ~4.8s to run with and without that change. I've made a PR for this (feel free to modify or ignore if there is a better way to do it, or I can do that too if you like).

**Comment by reactormonk** [comment]
This bug just cost me two days, so I wouldn't mind it being merged.

**Comment by ford-prefect** [comment]
Closed by #173
