### ISSUE TITLE
launchAff_ ∷ Aff Unit → Effect Unit

### ISSUE THREAD

**Issue by safareli** [purescript-contrib/purescript-aff#178]
It's very easy to accidentally discard values when with `launchAff_` it can produce dumb "bugs". I think it would be better to specialize it's type to:
```diff
-launchAff_ ∷ ∀ a. Aff a → Effect Unit
+launchAff_ ∷ Aff Unit → Effect Unit
```
Maybe we can do this in next braking change if people agree if people agree?

(This is what I was thinking before https://github.com/purescript/purescript-prelude/issues/203 but I got convinced with just specializing `a` to `Unit`)

**Comment by JordanMartinez** [comment]
Isn't that why `launchAff` exists?

`launchAff_` exists because it's less verbose than `void <<< launchAff`

So by choosing to use `launchAff_`, aren't you indicating that you don't
care what the return value is?

Or am I misunderstanding you?

**Comment by garyb** [comment]
Yeah, it's pretty much the whole point of `launchAff_` over `launchAff`. Similar to `traverse_`, `for_`, etc. where they discard any value also.
