### ISSUE TITLE
Different behavior of forkAff with/without delay

### ISSUE THREAD

**Issue by rnons** [purescript-contrib/purescript-aff#182]
## The code

```purescript
  traceM "hanlder start"
  void $ Aff.forkAff $ do
    -- output is differnt with / without Aff.delay
    -- Aff.delay $ Aff.Milliseconds 0.0
    traceM "fork start"
    buffer <- liftEffect $ ChildProcess.execSync
      "echo fork running"
      ChildProcess.defaultExecSyncOptions
    liftEffect $ Buffer.toString UTF8 buffer >>= \msg ->
      traceM msg
  traceM "hanlder finish"
```

## The output

Without `Aff.delay`, I get

```
'hanlder start'
'fork start'
'fork running\n'
'hanlder finish'
```

With `Aff.delay`, I get

```
'hanlder start'
'hanlder finish'
'fork start'
'fork running\n'
```

This is the desired behavior, however, not sure why `Aff.delay 0` is needed.

A reproducible repo is at https://github.com/rnons/fork-aff-issue

**Comment by garyb** [comment]
The ordering changes as adding the `Aff.delay` makes it asynchronous. If I remember rightly, it's intentional that forked synchronous code executes synchronously in `Aff`.

**Comment by natefaubion** [comment]
If you require a specific ordering of actions I'd recommend that you use an `AVar` to coordinate among fibers (or use a suspended fiber). It's not safe to rely on the whims of the scheduler.

**Comment by rnons** [comment]
It's not the specific ordering that I care, I want the forked code to not block the handler. The code example was a simplified version of a backend api handler. I want frontend to receive response before `forkAff` finishes.

**Comment by natefaubion** [comment]
It does not block the handler. You can't take ordering of synchronous log statements as evidence that it's blocking anything.

**Comment by natefaubion** [comment]
You are using execSync, so it will block regardless because JS is single threaded. That's why you should use the async API lifted into Aff instead.

**Comment by rnons** [comment]
> You should use the async API lifted into Aff instead.

Sorry, which one is async api?

**Comment by natefaubion** [comment]
The async API is `exec`, which uses callbacks and needs to be wrapped in `makeAff`. `execSync` is a fully synchronous API, and will block the entire JS runtime. There's nothing Aff can do about that. You might try https://github.com/justinwoo/purescript-sunde

**Comment by rnons** [comment]
Thanks
