### ISSUE TITLE
Instance Alternative ParAff does not abort when transformed by ExceptT

### ISSUE THREAD

**Issue by arthurxavierx** [purescript-contrib/purescript-aff#185]
This code does not produce the expected behavior:
```purescript
test :: forall e a. ExceptT e (Aff a)
test =
  sequential $ oneOfMap parallel
    [ never -- or `forever $ delay (Milliseconds 1000.0)
    , liftAff $ throwError (error "Test")
    ]

...

runAff (either (log <<< message) (pure unit)) test
```

I'd expect that calling `runAff` on `test` would log `"Test"` to the console, but that's not what happens. Instead, the handler callback is never called.

**Comment by natefaubion** [comment]
`oneOf` races the effects, so it returns the first one that completes successfully. Since one errors, and one blocks forever, it is expected that it would block forever.

**Comment by arthurxavierx** [comment]
Hm, sorry. I should've paid more attention to [this docstring](https://github.com/purescript-contrib/purescript-aff/blob/78916a9c7e6d203f1d9f441c8eaa257d6475e978/src/Effect/Aff.purs#L136). I've misread the part that says that it only returns the first error if **all** fail with an exception. I'd thought it said it'd return the first error if _any_ fails with an exception.
> Races effects in parallel. Returns the first successful result or the first error if all fail with an exception. Losing branches will be
cancelled.

Is there any way to achieve such behavior with `ParAff` and its `Alt` instance?

**Comment by natefaubion** [comment]
Something like:
```purescript
oneOfOrError = either throwError pure <=< parOneOfMap try
```

**Comment by arthurxavierx** [comment]
Ah right! Thank you :)
