### ISSUE TITLE
how to implement Aff a -> Effect a?

### ISSUE THREAD

**Issue by srghma** [purescript-contrib/purescript-aff#187]
how to properly implement `executeAff :: Aff a -> Effect a`? 

this is needed for https://github.com/purescript/purescript-psci-support/issues/16 and https://github.com/purescript/purescript-psci-support/pull/17

example usage

```
$ spago repl


import Selenium -- from purescript-webkit

-- it would open chrome and return driver
buildChromeDriver :: Aff Driver
buildChromeDriver = ...

> driver = unsafePerformEffect $ executeAff $ buildChromeDriver

> get driver "http://google.com"
```

**Comment by natefaubion** [comment]
`Aff` is asynchronous, so it's not possible to implement `Aff ~> Effect a`. To get the result you must give it a callback. Please see `runAff` and `launchAff`.

**Comment by srghma** [comment]
maybe it's possible to make some `unsafe` version, just for this usecase?

**Comment by garyb** [comment]
You could only make an `Aff a -> Effect Unit`, there would be no way to suspend execution for an async thing to complete and return a result. `launchAff_`, basically.

**Comment by natefaubion** [comment]
It's fundamentally impossible in general. The best you can do is `Aff a -> Effect Unit` which just spawns an async task, and is available as `launchAff_`. If you want the repl to support Aff (and wait until the Aff task is complete), then the repl runtime needs to be evented and support async evaluation.

**Comment by srghma** [comment]
yes, you right guys, it's not possible with `Aff` as it is not possible with js promises

tnx @natefaubion for a way to go
