### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by Mateiadrielrafael** [purescript-contrib/purescript-aff#212]
**Describe the bug**
I get the following error while trying to build the project: 
![image](https://user-images.githubusercontent.com/39400800/182544388-3b1d699e-84a8-4051-9158-854205fd794d.png)

**To Reproduce**
Clone the repo and run `spago build`

**Expected behavior**
The project should build

**Additional context**
![image](https://user-images.githubusercontent.com/39400800/182544683-40562959-bef7-4463-9fe9-c075f05a459f.png)

**Comment by Mateiadrielrafael** [comment]
Should I manually override the package set to something like 
```
https://github.com/purescript/package-sets/releases/download/psc-0.15.4-20220725/packages.dhall
        sha256:e56fbdf33a5afd2a610c81f8b940b413a638931edb41532164e641bb2a9ec29c
```

**Comment by JordanMartinez** [comment]
Yeah. That, or `spago upgrade-set` if it works. The `prepare-0.15` set was a temporary set used to update the ecosystem when doing the `0.15` breaking release.

**Comment by Mateiadrielrafael** [comment]
The additional context contains a screenshot of me attempting an upgrade- set:) I'll manually upgrade the set and open the pr tomorrow

**Comment by JordanMartinez** [comment]
Ah... Sorry about that.

Yeah, `spago` isn't the smartest when it looks for the package set. I believe it expects to find a prefix of `https://github.com/purescript/package-sets/releases/download/`, and if it doesn't it just bails.
